const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //VIENCHUC
  VIENCHUC_LOGIN_SUCCESS: "VIENCHUC_LOGIN_SUCCESS",
  VIENCHUC_LOGIN_FAIL: "VIENCHUC_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  BENHNHAN_LOGIN_SUCCESS: "BENHNHAN_LOGIN_SUCCESS",
  BENHNHAN_LOGIN_FAIL: "BENHNHAN_LOGIN_FAIL",
  PROCESS_BN_LOGOUT: "PROCESS_BN_LOGOUT",

  FETCH_XAPHUONG_START: "FETCH_XAPHUONG_START",
  FETCH_XAPHUONG_SUCCESS: "FETCH_XAPHUONG_SUCCESS",
  FETCH_XAPHUONG_FAIDED: "FETCH_XAPHUONG_FAIDED",

  FETCH_CHUYENKHOA_START: "FETCH_CHUYENKHOA_START",
  FETCH_CHUYENKHOA_SUCCESS: "FETCH_CHUYENKHOA_SUCCESS",
  FETCH_CHUYENKHOA_FAIDED: "FETCH_CHUYENKHOA_FAIDED",

  FETCH_TDHV_START: "FETCH_TDHV_START",
  FETCH_TDHV_SUCCESS: "FETCH_TDHV_SUCCESS",
  FETCH_TDHV_FAIDED: "FETCH_TDHV_FAIDED",

  FETCH_CHUCVU_START: "FETCH_CHUCVU_START",
  FETCH_CHUCVU_SUCCESS: "FETCH_CHUCVU_SUCCESS",
  FETCH_CHUCVU_FAIDED: "FETCH_CHUCVU_FAIDED",

  FETCH_XAPHUONG_START: "FETCH_XAPHUONG_START",
  FETCH_XAPHUONG_SUCCESS: "FETCH_XAPHUONG_SUCCESS",
  FETCH_XAPHUONG_FAIDED: "FETCH_XAPHUONG_FAIDED",

  FETCH_HUYENQUAN_START: "FETCH_HUYENQUAN_START",
  FETCH_HUYENQUAN_SUCCESS: "FETCH_HUYENQUAN_SUCCESS",
  FETCH_HUYENQUAN_FAIDED: "FETCH_HUYENQUAN_FAIDED",

  FETCH_TINHTHANH_START: "FETCH_TINHTHANH_START",
  FETCH_TINHTHANH_SUCCESS: "FETCH_TINHTHANH_SUCCESS",
  FETCH_TINHTHANH_FAIDED: "FETCH_TINHTHANH_FAIDED",

  FETCH_ALL_VIENCHUC_SUCCESS: "FETCH_ALL_VIENCHUC_SUCCESS",
  FETCH_ALL_VIENCHUC_FAIDED: "FETCH_ALL_VIENCHUC_FAIDED",

  CREATE_VIENCHUC_SUCCESS: "CREATE_VIENCHUC_SUCCESS",
  CREATE_VIENCHUC_FAIDED: "CREATE_VIENCHUC_FAIDED",

  EDIT_VIENCHUC_SUCCESS: "EDIT_VIENCHUC_SUCCESS",
  EDIT_VIENCHUC_FAIDED: "EDIT_VIENCHUC_FAIDED",

  DELETE_VIENCHUC_SUCCESS: "DELETE_VIENCHUC_SUCCESS",
  DELETE_VIENCHUC_FAIDED: "DELETE_VIENCHUC_FAIDED",

  FETCH_ALL_CHUYENKHOA_SUCCESS: "FETCH_ALL_CHUYENKHOA_SUCCESS",
  FETCH_ALL_CHUYENKHOA_FAIDED: "FETCH_ALL_CHUYENKHOA_FAIDED",

  CREATE_CHUYENKHOA_SUCCESS: "CREATE_CHUYENKHOA_SUCCESS",
  CREATE_CHUYENKHOA_FAIDED: "CREATE_CHUYENKHOA_FAIDED",

  EDIT_CHUYENKHOA_SUCCESS: "EDIT_CHUYENKHOA_SUCCESS",
  EDIT_CHUYENKHOA_FAIDED: "EDIT_CHUYENKHOA_FAIDED",

  DELETE_CHUYENKHOA_SUCCESS: "DELETE_CHUYENKHOA_SUCCESS",
  DELETE_CHUYENKHOA_FAIDED: "DELETE_CHUYENKHOA_FAIDED",

  FETCH_VIENCHUCCHUYENKHOATHANKINH_START:
    "FETCH_VIENCHUCCHUYENKHOATHANKINH_START",
  FETCH_VIENCHUCCHUYENKHOATHANKINH_SUCCESS:
    "FETCH_VIENCHUCCHUYENKHOATHANKINH_SUCCESS",
  FETCH_VIENCHUCCHUYENKHOATHANKINH_FAIDED:
    "FETCH_VIENCHUCCHUYENKHOATHANKINH_FAIDED",

  FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_START:
    "FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_START",
  FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_SUCCESS:
    "FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_SUCCESS",
  FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_FAIDED:
    "FETCH_VIENCHUCCHUYENKHOACOXUONGKHOP_FAIDED",

  FETCH_VIENCHUCCHUYENKHOATIEUHOA_START:
    "FETCH_VIENCHUCCHUYENKHOATIEUHOA_START",
  FETCH_VIENCHUCCHUYENKHOATIEUHOA_SUCCESS:
    "FETCH_VIENCHUCCHUYENKHOATIEUHOA_SUCCESS",
  FETCH_VIENCHUCCHUYENKHOATIEUHOA_FAIDED:
    "FETCH_VIENCHUCCHUYENKHOATIEUHOA_FAIDED",

  FETCH_VIENCHUCCHUYENKHOATIMMACH_START:
    "FETCH_VIENCHUCCHUYENKHOATIMMACH_START",
  FETCH_VIENCHUCCHUYENKHOATIMMACH_SUCCESS:
    "FETCH_VIENCHUCCHUYENKHOATIMMACH_SUCCESS",
  FETCH_VIENCHUCCHUYENKHOATIMMACH_FAIDED:
    "FETCH_VIENCHUCCHUYENKHOATIMMACH_FAIDED",

  FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_START:
    "FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_START",
  FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_SUCCESS:
    "FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_SUCCESS",
  FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_FAIDED:
    "FETCH_VIENCHUCCHUYENKHOATAIMUIHONG_FAIDED",

  FETCH_ALL_BUOI_SUCCESS: "FETCH_ALL_BUOI_SUCCESS",
  FETCH_ALL_BUOI_FAIDED: "FETCH_ALL_BUOI_FAIDED",

  CREATE_VIENCHUCCHUYENKHOATHANKINH_SUCCESS:
    "CREATE_VIENCHUCCHUYENKHOATHANKINH_SUCCESS",
  CREATE_VIENCHUCCHUYENKHOATHANKINH_FAIDED:
    "CREATE_VIENCHUCCHUYENKHOATHANKINH_FAIDED",

  EDIT_VIENCHUCCHUYENKHOATHANKINH_SUCCESS:
    "EDIT_VIENCHUCCHUYENKHOATHANKINH_SUCCESS",
  EDIT_VIENCHUCCHUYENKHOATHANKINH_FAIDED:
    "EDIT_VIENCHUCCHUYENKHOATHANKINH_FAIDED",

  DELETE_VIENCHUCCHUYENKHOATHANKINH_SUCCESS:
    "DELETE_VIENCHUCCHUYENKHOATHANKINH_SUCCESS",
  DELETE_VIENCHUCCHUYENKHOATHANKINH_FAIDED:
    "DELETE_VIENCHUCCHUYENKHOATHANKINH_FAIDED",

  FETCH_ALL_PHONGCHUYENKHOATHANKINH_SUCCESS:
    "FETCH_ALL_PHONGCHUYENKHOATHANKINH_SUCCESS",
  FETCH_ALL_PHONGCHUYENKHOATHANKINH_FAIDED:
    "FETCH_ALL_PHONGCHUYENKHOATHANKINH_FAIDED",

  FETCH_ALL_PHONGCHUYENKHOACOXUONGKHOP_SUCCESS:
    "FETCH_ALL_PHONGCHUYENKHOACOXUONGKHOP_SUCCESS",
  FETCH_ALL_PHONGCHUYENKHOACOXUONGKHOP_FAIDED:
    "FETCH_ALL_PHONGCHUYENKHOACOXUONGKHOP_FAIDED",

  FETCH_ALL_PHONGCHUYENKHOATIEUHOA_SUCCESS:
    "FETCH_ALL_PHONGCHUYENKHOATIEUHOA_SUCCESS",
  FETCH_ALL_PHONGCHUYENKHOATIEUHOA_FAIDED:
    "FETCH_ALL_PHONGCHUYENKHOATIEUHOA_FAIDED",

  FETCH_ALL_PHONGCHUYENKHOATIMMACH_SUCCESS:
    "FETCH_ALL_PHONGCHUYENKHOATIMMACH_SUCCESS",
  FETCH_ALL_PHONGCHUYENKHOATIMMACH_FAIDED:
    "FETCH_ALL_PHONGCHUYENKHOATIMMACH_FAIDED",

  FETCH_ALL_PHONGCHUYENKHOATAIMUIHONG_SUCCESS:
    "FETCH_ALL_PHONGCHUYENKHOATAIMUIHONG_SUCCESS",
  FETCH_ALL_PHONGCHUYENKHOATAIMUIHONG_FAIDED:
    "FETCH_ALL_PHONGCHUYENKHOATAIMUIHONG_FAIDED",

  FETCH_ALL_BACSI_SUCCESS: "FETCH_ALL_BACSI_SUCCESS",
  FETCH_ALL_BACSI_FAIDED: "FETCH_ALL_BACSI_FAIDED",

  FETCH_ALL_HOATCHAT_START: "FETCH_ALL_HOATCHAT_START",
  FETCH_ALL_HOATCHAT_SUCCESS: "FETCH_ALL_HOATCHAT_SUCCESS",
  FETCH_ALL_HOATCHAT_FAIDED: "FETCH_ALL_HOATCHAT_FAIDED",

  FETCH_ALL_NHASX_START: "FETCH_ALL_NHASX_START",
  FETCH_ALL_NHASX_SUCCESS: "FETCH_ALL_NHASX_SUCCESS",
  FETCH_ALL_NHASX_FAIDED: "FETCH_ALL_NHASX_FAIDED",

  FETCH_ALL_THUOC_START: "FETCH_ALL_THUOC_START",
  FETCH_ALL_THUOC_SUCCESS: "FETCH_ALL_THUOC_SUCCESS",
  FETCH_ALL_THUOC_FAIDED: "FETCH_ALL_THUOC_FAIDED",

  /// temp
  FETCH_TEPM: "FETCH_TEPM",
  FETCH_TEPM_SUCCESS: "FETCH_TEPM_SUCCESS",
  FETCH_TEPM_FAIDED: "FETCH_TEPM_FAIDED",

  // temp search dịch vụ
  FETCH_TEPM_SEARCH: "FETCH_TEPM_SEARCH",
  FETCH_TEPM_SEARCH_SUCCESS: "FETCH_TEPM_SEARCH_SUCCESS",
  FETCH_TEPM_SEARCH_FAIDED: "FETCH_TEPM_SEARCH_FAIDED",
});

export default actionTypes;
